name: Test GPR Push
on: push

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:

    - name: Copy Repo Files
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Publish Docker Image to GPR
      uses: ./
      with:
        IMAGE_NAME: 'test-docker-action-v2'
        TAG: 'my-optional-tag-name'
        DOCKERFILE_PATH: 'Dockerfile'
        BUILD_CONTEXT: '.'
      env:
        REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
